services:
  - type: web
    name: antarctica-twin-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://tejashwini967_db_user:DKN2a2lkDvuMpwsw@cluster0.q6np1kn.mongodb.net/DigiAI-ICE-TWIN?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: antarctica-digital-twin-secret-key-2026
      - key: NODE_ENV
        value: production
