import mongoose from "mongoose";

// One reading = one snapshot from a simulated sensor. In production these
// would arrive from real station hardware; here they're generated by
// simulator.js on an interval so the dashboard and twin feel alive.
const telemetrySchema = new mongoose.Schema(
  {
    stationCode: { type: String, required: true, index: true },
    zoneId: { type: String, required: true },
    metric: {
      type: String,
      enum: [
        "temperature_c",
        "wind_speed_kmh",
        "power_load_kw",
        "generator_health_pct",
        "battery_pct",
        "fuel_flow_lph",
        "water_level_pct",
        "internal_temp_c",
      ],
      required: true,
    },
    value: { type: Number, required: true },
    threshold: {
      warning: Number,
      critical: Number,
    },
    recordedAt: { type: Date, default: Date.now, index: true },
    // set true when this reading was created client-side while offline and
    // later synced — used to demonstrate the offline-first flow in the demo
    syncedFromOffline: { type: Boolean, default: false },
  },
  { timestamps: true }
);

telemetrySchema.index({ stationCode: 1, metric: 1, recordedAt: -1 });

export default mongoose.model("Telemetry", telemetrySchema);
